In [6]:
import os
import glob
import pandas as pd
import time
from PIL import Image

In [7]:
verbosity     = 1
which_dataset = 1

In [8]:
if   which_dataset == 0:
    root_dir = "/home/khairulimam/datasets/vggv2/train-mtcnn-182/"
elif which_dataset == 1:
    root_dir = "/home/khairulimam/datasets/vggv2/test-mtcnn-182/"
elif which_dataset == 2:
    root_dir = "/home/khairulimam/datasets/lfw-mtcnn-182/"
elif which_dataset == 3:
    root_dir = "facescrub/train/"
elif which_dataset == 4:
    root_dir = "facescrub/valid/"
else:
    root_dir = "/run/media/hoosiki/WareHouse2/home/mtb/datasets/my_pictures/my_pictures_mtcnnpy_182"

In [9]:
files = glob.glob(root_dir+"/*/*")
len(files)

169178

In [10]:
time0 = time.time()
df = pd.DataFrame()
print("The number of files: ", len(files))
for idx, file in enumerate(files):
    if idx%10000 == 0:
        print("[{}/{}]".format(idx, len(files)-1))
    '''    
    try:
        img = Image.open(file) # open the image file
        img.verify() # verify that it is, in fact, an image
    except (IOError, SyntaxError) as e:
        if verbosity == 1:
            print('Bad file:', file) # print out the names of corrupt files
        pass
    else:
        face_id    = os.path.basename(file).split('.')[0]
        face_label = os.path.basename(os.path.dirname(file))
        df = df.append({'id': face_id, 'name': face_label}, ignore_index = True)
    '''    
    extension = file.split('.')[-1]
    face_id    = os.path.basename(file).split('.')[0]
    face_label = os.path.basename(os.path.dirname(file))
    df = df.append({'id': face_id, 'name': face_label, 'ext': extension}, ignore_index = True)

The number of files:  169178
[0/169177]
[10000/169177]
[20000/169177]
[30000/169177]
[40000/169177]
[50000/169177]
[60000/169177]
[70000/169177]
[80000/169177]
[90000/169177]
[100000/169177]
[110000/169177]
[120000/169177]
[130000/169177]
[140000/169177]
[150000/169177]
[160000/169177]

In [11]:
df = df.sort_values(by = ['name', 'id']).reset_index(drop = True)

In [12]:
df['class'] = pd.factorize(df['name'])[0]

In [13]:
if which_dataset == 0:
    df.to_csv("train_vggface2.csv", index = False)
elif which_dataset == 1:
    df.to_csv("test_vggface2.csv", index = False)
elif which_dataset == 2:
    df.to_csv("valid_lfw.csv", index = False)
elif which_dataset == 3:
    df.to_csv("train_facescrub.csv", index = False)
elif which_dataset == 4:
    df.to_csv("valid_facescrub.csv", index = False)
else:
    df.to_csv("my_pictures.csv", index = False)

elapsed_time = time.time() - time0
print("elapsted time: ", elapsed_time//3600, "h", elapsed_time%3600//60, "m")

elapsted time:  0.0 h 27.0 m

In [14]:
df

        ext       id     name  class
0       jpg  0001_01  n000001      0
1       jpg  0002_01  n000001      0
2       jpg  0003_01  n000001      0
3       jpg  0004_01  n000001      0
4       jpg  0005_01  n000001      0
5       jpg  0006_01  n000001      0
6       jpg  0007_01  n000001      0
7       jpg  0008_01  n000001      0
8       jpg  0009_01  n000001      0
9       jpg  0010_01  n000001      0
10      jpg  0011_01  n000001      0
11      jpg  0012_01  n000001      0
12      jpg  0013_01  n000001      0
13      jpg  0014_01  n000001      0
14      jpg  0015_01  n000001      0
15      jpg  0016_01  n000001      0
16      jpg  0017_01  n000001      0
17      jpg  0018_01  n000001      0
18      jpg  0019_01  n000001      0
19      jpg  0020_01  n000001      0
20      jpg  0021_01  n000001      0
21      jpg  0022_01  n000001      0
22      jpg  0023_01  n000001      0
23      jpg  0024_01  n000001      0
24      jpg  0025_01  n000001      0
25      jpg  0026_02  n000001      0
26      jpg  0027_03  n000001      0
27      jpg  0028_01  n000001      0
28      jpg  0029_01  n000001      0
29      jpg  0030_01  n000001      0
...     ...      ...      ...    ...
169148  jpg  0254_02  n009294    499
169149  jpg  0255_01  n009294    499
169150  jpg  0256_01  n009294    499
169151  jpg  0257_01  n009294    499
169152  jpg  0258_01  n009294    499
169153  jpg  0259_01  n009294    499
169154  jpg  0260_01  n009294    499
169155  jpg  0261_02  n009294    499
169156  jpg  0263_01  n009294    499
169157  jpg  0264_02  n009294    499
169158  jpg  0265_01  n009294    499
169159  jpg  0266_01  n009294    499
169160  jpg  0267_01  n009294    499
169161  jpg  0268_01  n009294    499
169162  jpg  0269_09  n009294    499
169163  jpg  0270_03  n009294    499
169164  jpg  0271_02  n009294    499
169165  jpg  0273_01  n009294    499
169166  jpg  0274_02  n009294    499
169167  jpg  0276_01  n009294    499
169168  jpg  0279_02  n009294    499
169169  jpg  0280_02  n009294    499
169170  jpg  0281_01  n009294    499
169171  jpg  0282_01  n009294    499
169172  jpg  0282_03  n009294    499
169173  jpg  0284_01  n009294    499
169174  jpg  0287_01  n009294    499
169175  jpg  0289_01  n009294    499
169176  jpg  0290_02  n009294    499
169177  jpg  0291_01  n009294    499

[169178 rows x 4 columns]